spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filemanager?serverTimezone=UTC
    username: root
    password:
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true
  jpa:
    database: mysql
    show-sql: true